### ISSUE TITLE
Angular Universal Does not work with some plugins

### ISSUE THREAD

**Issue by blaybel** [m98/universal-cli-starter#2]
Dear Mohammad,
Thanks for this post it is really helpful, but I have a problem when I use plugins like **_ngx-scrollspy_** or _**ng2-scroll-to-el**_ and run the command **_npm run serve:universal_** i got this error: 

```
universal-cli-starter-master\node_modules\ngx-scrollspy\dist\core\service.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable, EventEmitter } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.2IYf (C:\Users\ABlaybel\Desktop\test angular 2\universal\10-2-2017\universal-cli-starter-master\dist\dist-server\main.bundle.js:1:649)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve:universal"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! universal-cli@0.0.0 serve:universal: `npm run build:universal && cd dist && node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the universal-cli@0.0.0 serve:universal script 'npm run build:universal && cd dist && node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the universal-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:universal && cd dist && node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs universal-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls universal-cli
npm ERR! There is likely additional logging output above.
```

**Comment by m98** [comment]
Hey,
You're welcome.

Unfortunately, some modules cause problems with server-side rendering!

For scroll, I use [ngx-infinite-scroll](https://github.com/orizens/ngx-infinite-scroll) which works as expected in my case.
