### ISSUE TITLE
How to deploy on server

### ISSUE THREAD

**Issue by Gajendrasinh** [m98/universal-cli-starter#3]
I have run this "npm run build:universal" and i received dist folder

npm run build:universal: Build the client and server application. For running the server, open the dist directory (cd dist) and run the server.js by using node server.js, it will serve the application on localhost:8000

i have copy only dist folder and paste on my server nginx and i was running node server.js

its give me error 

 node server.js

module.js:540
    throw err;
    ^
Error: Cannot find module 'rxjs/symbol/observable'
    at Function.Module._resolveFilename (module.js:538:15) [<root>]
    at Function.Module._load (module.js:468:25) [<root>]
    at Module.require (module.js:587:17) [<root>]
    at require (internal/module.js:11:18) [<root>]
    at globalScope (/Users/indianic/node_modules/@angular/core/bundles/core.umd.js:7:85) [<root>]
    at Object.<anonymous> (/Users/indianic/node_modules/@angular/core/bundles/core.umd.js:10:2) [<root>]
    at Module._compile (module.js:643:30) [<root>]
    at Object.Module._extensions..js (module.js:654:10) [<root>]
    at Module.load (module.js:556:32) [<root>]
    at tryModuleLoad (module.js:499:12) [<root>]
    at Function.Module._load (module.js:491:3) [<root>]
    at Module.require (module.js:587:17) [<root>]
    at require (internal/module.js:11:18) [<root>]
    at Object.setPrototypeOf.__proto__ (/Users/indianic/node_modules/@angular/platform-server/bundles/platform-server.umd.js:7:82) [<root>]

**Comment by m98** [comment]
You need node_modules if you use this project, otherwise, you need to use [this repository](https://github.com/angular/universal-starter) as they solved this problem and it works very well. My idea of creating this repository was letting people understand what does server-side rendering mean, and it's not necessarily the best practice.

**Comment by nazar222** [comment]
Hello, Thanks for great explanation. 
I have followed all the steps from your tutorial. And then copied the node_module inside the /dist directory then used "node server.js" and it is giving the following error in server. (Working in my locahost) : 

> const { platformServer, renderModuleFactory } = require('@angular/platform-server');
>           ^
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3

I have spent my whole day but no clue. Thanks.
